# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nishant | Portfolio
email: nishant.madu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Front-End Web Developer,specialising in HTML,CSS,JavaScript and AngularJS:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: nishanthmadu
github_username:  nishantmadu
google_username: nishantmadu

permalink: /:categories/:title

links:
- title: about
  url: /about

- title: work
  url: /work

- title: hire me
  url: /hire-me

# Build settings
markdown: kramdown
